source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

target 'MantleExtensionDemo' do
    
    platform :ios, ‘8.0’
    use_frameworks!
    
    pod 'MantleExtension', :git => 'https://github.com/MarkeJave/Mantle-Extenssion.git', :tag => '1.0.0'
end
